<?php

/**
 * Implements hook_autoload_info().
 */
function halloween_lights_autoload_info() {
  return array(
    'BlockHalloweenLights' => 'includes/block.halloween_lights.inc',
  );
}

/**
 * Prepares variables for site alert blocks.
 */
/*function halloween_lights_preprocess_block(&$variables) {
  $block = $variables['block'];
  if (get_class($block) == 'BlockHalloweenLights') {
    if (isset($block->settings['halloweenlights'])) {
      $variables['classes'][] = 'block-halloween-lights';
    }
  }
}*/

/**
 * Implements hook_preprocess_HOOK().
().
 */
function halloween_lights_preprocess_page(&$variables) {
  if ((!path_is_admin(current_path()))) {
    $path = backdrop_get_path('module', 'halloween_lights');
    backdrop_add_css($path . '/css/pumpkin.css');
    backdrop_add_js($path . '/js/pumpkin.js');
  }
}

/**
 * Implements hook_block_info().
 */
function halloween_lights_block_info() {
  $blocks = array();
  $default_info = t('Add Halloween Lights.');
  $blocks['default'] = array(
    // The name that will appear in the block list.
    'info' => t('Halloween Lights Block'),
    'description' => $default_info,
    'class' => 'BlockHalloweenLights',
  );
  return $blocks;
}




