<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */
function halloween_lights_page_attachments(array &$attachments) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if (!$is_admin) {
    $attachments['#attached']['library'][] = 'halloween_lights/pumpkin';
  }
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
/*function halloween_lights_preprocess_page(&$variables) {
    $variables['#attached']['library'][] = 'halloween_lights/pumpkin';
}*/




